import = [ "~/.config/alacritty/tokyonight.toml" ]
live_config_reload = true

[shell]
program = "/bin/zsh"
args = [ "-l" ]

[window]
dynamic_padding = true

  [window.dimensions]
  columns = 120
  lines = 36

  [window.padding]
  x = 6
  y = 18

[scrolling]
history = 10_000
multiplier = 20

[font]
size = 14

  [font.normal]
  family = "FiraCode Nerd Font Mono"
  style = "Regular"

  [font.bold]
  family = "FiraCode Nerd Font Mono"
  style = "Bold"

  [font.italic]
  family = "FiraCode Nerd Font Mono"
  style = "Italic"

  [font.offset]
  x = 1
  y = 6

[cursor.style]
shape = "Underline"
blinking = "on"


